/** Immutable flashcard deck, card, source and session contracts. */
export type FlashcardSourceVisual = { caption: string; altText: string; contentUrl: string };
export type FlashcardSource = { chunkRef: string; documentTitle: string; page: number; printedPage?: string | null; passage: string; paragraphs?: string[]; visual?: FlashcardSourceVisual | null; textbookPageUrl?: string | null };
export type FlashcardCard = { cardRef: string; ordinal: number; version: number; front: string; back?: string | null; explanation?: string | null; status: string; warnings: string[]; source: FlashcardSource; conceptKey: string; category: string; variationType: string; difficulty: 'easy'|'difficult'; selectedRating?: FlashcardRating | null; attempted: boolean };
export type FlashcardDeck = { deckRef: string; topicRef: string; topicCode: string; topicTitle: string; groupCode: string; groupTitle: string; subjectId: string; title: string; status: string; contentVersion: number; cardCount: number; approvedCount: number; reviewRequiredCount: number; rejectedCount: number; cards: FlashcardCard[]; releasedAt?: string | null; releaseId?: string | null; artifactChecksum?: string | null; validationStatus?: string | null; categoryDistribution: Record<string, number>; validationSummary: Record<string, unknown> };
export type FlashcardMode = 'review'|'difficult';
export type FlashcardDifficulty = 'easy'|'difficult'|'mixed';
export type FlashcardRating = 'again'|'difficult'|'good'|'easy';
export type FlashcardStudyOption = { mode: FlashcardMode; title: string; description: string; availableCount: number; sessionSize: number; enabled: boolean; supportedCounts: number[]; difficulties: FlashcardDifficulty[] };
export type FlashcardStudyOptions = { deckRef: string; options: FlashcardStudyOption[]; summary: Record<string, number> };
export type FlashcardSession = { sessionRef: string; deck: FlashcardDeck; status: string; currentOrdinal: number; reviewedCount: number; totalCards: number; currentCard?: FlashcardCard | null; answerRevealed: boolean; masteryVersion: string; selectionVersion: string; message: string; mode: FlashcardMode; difficulty?: FlashcardDifficulty | null; selectionReasons: string[]; viewedOrdinal: number; firstUnattemptedOrdinal: number; canGoPrevious: boolean; canGoNext: boolean; hasUncommittedResults: boolean };
export type FlashcardMasteryCategory = { category: string; total: number; toEvaluate: number; needsReview: number; good: number; mastered: number; coveragePercent: number; masteryPercent: number };
export type FlashcardMastery = { deckRef: string; totalCards: number; toEvaluate: number; needsReview: number; good: number; mastered: number; coveragePercent: number; masteryPercent: number; categories: FlashcardMasteryCategory[]; completedSessions: number; recentSessions: { sessionRef: string; mode: FlashcardMode; difficulty: FlashcardDifficulty | null; cardCount: number; completedAt: string }[]; recommendedMode: FlashcardMode; recommendedDifficulty: FlashcardDifficulty | null; recommendedCount: 20 | 30; masteryVersion: string; recalculatedAt?: string | null };
