"""Generate the committed OpenAPI document and dependency-free TypeScript contract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.main import app


BACKEND_ROOT = Path(__file__).resolve().parents[1]
OPENAPI_PATH = BACKEND_ROOT / "docs" / "openapi.json"
TYPESCRIPT_PATH = BACKEND_ROOT.parent / "frontend" / "lib" / "generated" / "api-contract.ts"


def ts_type(schema: dict[str, Any] | bool | None) -> str:
    if not schema:
        return "unknown"
    if schema is True:
        return "unknown"
    if "$ref" in schema:
        return f'Schemas["{schema["$ref"].rsplit("/", 1)[-1]}"]'
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "oneOf" in schema:
        return " | ".join(ts_type(item) for item in schema["oneOf"])
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join("null" if item == "null" else ts_type({**schema, "type": item}) for item in schema_type)
    if schema_type == "array":
        return f"Array<{ts_type(schema.get('items'))}>"
    if schema_type == "object" or "properties" in schema:
        required = set(schema.get("required", []))
        properties = schema.get("properties", {})
        fields = [
            f"{json.dumps(name)}{'?' if name not in required else ''}: {ts_type(value)};"
            for name, value in properties.items()
        ]
        if schema.get("additionalProperties"):
            fields.append(f"[key: string]: {ts_type(schema['additionalProperties'])};")
        return "{ " + " ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(
        schema_type, "unknown"
    )


def media_schema(container: dict[str, Any] | None) -> dict[str, Any] | None:
    if not container:
        return None
    content = container.get("content", {})
    return (content.get("application/json") or {}).get("schema")


def generate_typescript(spec: dict[str, Any]) -> str:
    schemas = spec.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by `python -m app.generate_api_contract`; do not edit by hand.",
        "",
        "export interface Schemas {",
    ]
    for name, schema in sorted(schemas.items()):
        lines.append(f"  {json.dumps(name)}: {ts_type(schema)};")
    lines.extend(["}", "", "export interface ApiOperations {"])
    for path, path_item in sorted(spec["paths"].items()):
        for method in ("get", "post", "put", "patch", "delete"):
            operation = path_item.get(method)
            if not operation:
                continue
            request_schema = media_schema(operation.get("requestBody"))
            success = next(
                (response for status, response in operation.get("responses", {}).items() if status.startswith("2")),
                None,
            )
            response_schema = media_schema(success)
            key = f"{method.upper()} {path}"
            lines.append(
                f"  {json.dumps(key)}: {{ request: {ts_type(request_schema)}; response: {ts_type(response_schema)} }};"
            )
    lines.extend(["}", "", "export type ApiOperation = keyof ApiOperations;", ""])
    return "\n".join(lines)


def generated_files() -> dict[Path, str]:
    spec = app.openapi()
    return {
        OPENAPI_PATH: json.dumps(spec, indent=2, sort_keys=True) + "\n",
        TYPESCRIPT_PATH: generate_typescript(spec),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when committed contracts are stale")
    args = parser.parse_args()
    stale: list[Path] = []
    for path, content in generated_files().items():
        if args.check:
            if not path.is_file() or path.read_text() != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"Generated {path}")
    if stale:
        names = ", ".join(str(path.relative_to(BACKEND_ROOT.parent)) for path in stale)
        raise SystemExit(f"Generated API contracts are stale: {names}")


if __name__ == "__main__":
    main()
