"""add deterministic document extraction

Revision ID: 37308ed3ea42
Revises: 73eec4d0d322
Create Date: 2026-09-13 08:43:11.964941
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37308ed3ea42'
down_revision: Union[str, None] = '73eec4d0d322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_document_asset_version', 'document_assets', ['id', 'document_version_id'])
    op.create_table('document_pages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('width_points', sa.Float(), nullable=False),
    sa.Column('height_points', sa.Float(), nullable=False),
    sa.Column('render_asset_id', sa.Uuid(), nullable=False),
    sa.Column('native_text', sa.Text(), server_default='', nullable=False),
    sa.Column('extraction_method', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('page_metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_document_pages_confidence'),
    sa.CheckConstraint('page_number > 0', name='ck_document_pages_number'),
    sa.CheckConstraint('width_points > 0 AND height_points > 0', name='ck_document_pages_dimensions'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['render_asset_id', 'document_version_id'], ['document_assets.id', 'document_assets.document_version_id'], name='fk_document_page_render_asset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_version_id', 'page_number', name='uq_document_page_number'),
    sa.UniqueConstraint('id', 'document_version_id', name='uq_document_page_version'),
    sa.UniqueConstraint('render_asset_id')
    )
    op.create_index(op.f('ix_document_pages_document_version_id'), 'document_pages', ['document_version_id'], unique=False)
    op.create_table('document_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_version_id', sa.Uuid(), nullable=False),
    sa.Column('page_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('block_kind', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('latex', sa.Text(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=False),
    sa.Column('extraction_method', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source_asset_id', sa.Uuid(), nullable=True),
    sa.Column('block_metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_kind IN ('heading','paragraph','table','question','subpart','answer_space','equation','image','diagram')", name='ck_document_blocks_kind'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_document_blocks_confidence'),
    sa.CheckConstraint('sequence_number > 0', name='ck_document_blocks_sequence'),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id', 'document_version_id'], ['document_pages.id', 'document_pages.document_version_id'], name='fk_document_block_page_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_asset_id', 'document_version_id'], ['document_assets.id', 'document_assets.document_version_id'], name='fk_document_block_source_asset_version', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id', 'sequence_number', name='uq_document_block_sequence')
    )
    op.create_index(op.f('ix_document_blocks_block_kind'), 'document_blocks', ['block_kind'], unique=False)
    op.create_index(op.f('ix_document_blocks_document_version_id'), 'document_blocks', ['document_version_id'], unique=False)
    op.create_index(op.f('ix_document_blocks_page_id'), 'document_blocks', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_blocks_page_id'), table_name='document_blocks')
    op.drop_index(op.f('ix_document_blocks_document_version_id'), table_name='document_blocks')
    op.drop_index(op.f('ix_document_blocks_block_kind'), table_name='document_blocks')
    op.drop_table('document_blocks')
    op.drop_index(op.f('ix_document_pages_document_version_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_constraint('uq_document_asset_version', 'document_assets', type_='unique')
    # ### end Alembic commands ###
