"""add explainable unit mastery

Revision ID: b0bea02e8860
Revises: ea52940bc7e7
Create Date: 2026-09-14 06:18:42.977383
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0bea02e8860'
down_revision: Union[str, None] = 'ea52940bc7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_mastery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('display_score', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('confidence', sa.String(length=12), nullable=False),
    sa.Column('provisional', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('evidence_weight', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.Column('variety_count', sa.Integer(), nullable=False),
    sa.Column('trend', sa.Numeric(precision=8, scale=5), server_default='0', nullable=False),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_number', sa.Integer(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("confidence IN ('low','medium','high')", name='ck_unit_mastery_confidence'),
    sa.CheckConstraint('evidence_count >= 0 AND evidence_weight >= 0 AND variety_count >= 0 AND version_number > 0', name='ck_unit_mastery_counts'),
    sa.CheckConstraint('score BETWEEN 0 AND 10 AND display_score BETWEEN 0 AND 10', name='ck_unit_mastery_score'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['textbook_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'unit_id', name='uq_unit_mastery_student_unit')
    )
    op.create_index(op.f('ix_unit_mastery_student_id'), 'unit_mastery', ['student_id'], unique=False)
    op.create_index(op.f('ix_unit_mastery_subject_id'), 'unit_mastery', ['subject_id'], unique=False)
    op.create_index(op.f('ix_unit_mastery_unit_id'), 'unit_mastery', ['unit_id'], unique=False)
    op.create_table('unit_mastery_dimensions',
    sa.Column('mastery_id', sa.Uuid(), nullable=False),
    sa.Column('dimension', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('evidence_weight', sa.Numeric(precision=10, scale=5), nullable=False),
    sa.CheckConstraint("dimension IN ('knowledge','application','method','accuracy','reasoning','communication','retention')", name='ck_unit_mastery_dimension_name'),
    sa.CheckConstraint('score BETWEEN 0 AND 10 AND evidence_weight >= 0', name='ck_unit_mastery_dimension_values'),
    sa.ForeignKeyConstraint(['mastery_id'], ['unit_mastery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mastery_id', 'dimension')
    )
    op.create_table('assessment_interactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('hint')", name='ck_assessment_interaction_kind'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id', 'request_key', name='uq_assessment_interaction_request')
    )
    op.create_index(op.f('ix_assessment_interactions_assessment_id'), 'assessment_interactions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_interactions_question_id'), 'assessment_interactions', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_interactions_student_id'), 'assessment_interactions', ['student_id'], unique=False)
    op.create_table('unit_mastery_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mastery_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_result_id', sa.Uuid(), nullable=False),
    sa.Column('previous_score', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('new_score', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('previous_confidence', sa.String(length=12), nullable=True),
    sa.Column('new_confidence', sa.String(length=12), nullable=False),
    sa.Column('contribution', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('new_score BETWEEN 0 AND 10', name='ck_unit_mastery_event_new'),
    sa.CheckConstraint('previous_score IS NULL OR previous_score BETWEEN 0 AND 10', name='ck_unit_mastery_event_previous'),
    sa.ForeignKeyConstraint(['mastery_id'], ['unit_mastery.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trigger_result_id'], ['assessment_results.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['textbook_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'trigger_result_id', name='uq_unit_mastery_event_trigger')
    )
    op.create_index(op.f('ix_unit_mastery_events_created_at'), 'unit_mastery_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_unit_mastery_events_mastery_id'), 'unit_mastery_events', ['mastery_id'], unique=False)
    op.create_index(op.f('ix_unit_mastery_events_student_id'), 'unit_mastery_events', ['student_id'], unique=False)
    op.create_index(op.f('ix_unit_mastery_events_trigger_result_id'), 'unit_mastery_events', ['trigger_result_id'], unique=False)
    op.create_index(op.f('ix_unit_mastery_events_unit_id'), 'unit_mastery_events', ['unit_id'], unique=False)
    op.add_column('assessment_questions', sa.Column('unit_weights', sa.JSON(), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_questions', 'unit_weights')
    op.drop_index(op.f('ix_unit_mastery_events_unit_id'), table_name='unit_mastery_events')
    op.drop_index(op.f('ix_unit_mastery_events_trigger_result_id'), table_name='unit_mastery_events')
    op.drop_index(op.f('ix_unit_mastery_events_student_id'), table_name='unit_mastery_events')
    op.drop_index(op.f('ix_unit_mastery_events_mastery_id'), table_name='unit_mastery_events')
    op.drop_index(op.f('ix_unit_mastery_events_created_at'), table_name='unit_mastery_events')
    op.drop_table('unit_mastery_events')
    op.drop_index(op.f('ix_assessment_interactions_student_id'), table_name='assessment_interactions')
    op.drop_index(op.f('ix_assessment_interactions_question_id'), table_name='assessment_interactions')
    op.drop_index(op.f('ix_assessment_interactions_assessment_id'), table_name='assessment_interactions')
    op.drop_table('assessment_interactions')
    op.drop_table('unit_mastery_dimensions')
    op.drop_index(op.f('ix_unit_mastery_unit_id'), table_name='unit_mastery')
    op.drop_index(op.f('ix_unit_mastery_subject_id'), table_name='unit_mastery')
    op.drop_index(op.f('ix_unit_mastery_student_id'), table_name='unit_mastery')
    op.drop_table('unit_mastery')
    # ### end Alembic commands ###
