"""add adaptive study plans

Revision ID: d661c1b505e4
Revises: aea6ead467da
Create Date: 2026-09-14 07:47:48.727035
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd661c1b505e4'
down_revision: Union[str, None] = 'aea6ead467da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('evidence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('generation_reason', sa.String(length=20), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("generation_reason IN ('evidence','request')", name='ck_study_plan_reason'),
    sa.CheckConstraint("status IN ('active','superseded')", name='ck_study_plan_status'),
    sa.CheckConstraint('version_number > 0', name='ck_study_plan_version'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'version_number', name='uq_study_plan_student_version')
    )
    op.create_index(op.f('ix_study_plans_status'), 'study_plans', ['status'], unique=False)
    op.create_index(op.f('ix_study_plans_student_id'), 'study_plans', ['student_id'], unique=False)
    op.create_index('uq_study_plan_active_student', 'study_plans', ['student_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('study_plan_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('success_condition', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned','completed')", name='ck_study_plan_item_status'),
    sa.CheckConstraint('sequence > 0 AND duration_minutes BETWEEN 5 AND 120', name='ck_study_plan_item_values'),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['improvement_recommendations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['retrieval_chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['textbook_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'recommendation_id', name='uq_study_plan_item_recommendation'),
    sa.UniqueConstraint('plan_id', 'sequence', name='uq_study_plan_item_sequence')
    )
    op.create_index(op.f('ix_study_plan_items_plan_id'), 'study_plan_items', ['plan_id'], unique=False)
    op.create_index(op.f('ix_study_plan_items_status'), 'study_plan_items', ['status'], unique=False)
    op.create_index(op.f('ix_study_plan_items_student_id'), 'study_plan_items', ['student_id'], unique=False)
    op.create_index(op.f('ix_study_plan_items_subject_id'), 'study_plan_items', ['subject_id'], unique=False)
    op.create_index(op.f('ix_study_plan_items_unit_id'), 'study_plan_items', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plan_items_unit_id'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_subject_id'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_student_id'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_status'), table_name='study_plan_items')
    op.drop_index(op.f('ix_study_plan_items_plan_id'), table_name='study_plan_items')
    op.drop_table('study_plan_items')
    op.drop_index('uq_study_plan_active_student', table_name='study_plans', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_study_plans_student_id'), table_name='study_plans')
    op.drop_index(op.f('ix_study_plans_status'), table_name='study_plans')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
