'use client';
/* eslint-disable react/react-compiler */
import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Empty, Heading } from './shared';
import { errorMessage, getTutorHistorySummaries, getTutorSafetyEvents, getTutorSupportTranscript, previewTutorTranscriptPurge, purgeTutorTranscripts, reviewTutorSafetyEvent, type TutorHistorySummary, type TutorSafetyEvent } from '@/api';

export function TutorHistory({ admin = false, notify }: { admin?: boolean; notify: (message: string) => void }) {
  const [summaries, setSummaries] = useState<TutorHistorySummary[]>([]), [events, setEvents] = useState<TutorSafetyEvent[]>([]);
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [reason, setReason] = useState(''), [days, setDays] = useState('365');
  const [preview, setPreview] = useState<{ turnCount: number; sessionCount: number; cutoff: string } | null>(null);
  const [transcript, setTranscript] = useState<{ studentName: string; turns: { turnRef: string; role: string; content: string; purged: boolean }[] } | null>(null);
  const load = useCallback(async () => { try { const [history, safety] = await Promise.all([getTutorHistorySummaries(), getTutorSafetyEvents()]); setSummaries(history.summaries); setEvents(safety.events); setError(''); } catch (cause) { setError(errorMessage(cause)); } }, []);
  useEffect(() => { void load(); }, [load]);
  const run = async (action: () => Promise<unknown>, message: string) => { setBusy(true); setError(''); try { await action(); await load(); notify(message); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } };
  return <div className="stack"><Heading eyebrow={admin ? 'ADMIN · CONTROLLED SUPPORT' : 'PARENT · TUTOR HISTORY'} title={admin ? 'Tutor history and safety' : 'Learning summaries and safety notices'}>{admin ? 'Support access and transcript cleanup are always reason-required and audited.' : 'Educational summaries protect the child’s private conversation while keeping you informed.'}</Heading>
    {error && <div className="error" role="alert">{error}</div>}
    <section className="panel stack"><h2>Session summaries</h2>{summaries.length ? summaries.map((item) => <article className="card stack" key={item.summaryRef}><div className="spread"><h3>{item.studentName} · {item.subjectId.toUpperCase()}</h3><small>{new Date(item.createdAt).toLocaleString()}</small></div><p><strong>Topics:</strong> {item.topicsCovered.map((topic) => `${topic.code} · ${topic.title}`).join(', ')}</p><p><strong>Activities:</strong> {item.activities.join(', ')}</p><p><strong>Strengths:</strong> {item.strengths.join(' ') || 'More evidence is needed.'}</p><p><strong>Difficulties:</strong> {item.difficulties.join(' ') || 'No verified difficulty was recorded.'}</p><p><strong>Next:</strong> {item.suggestedNextSteps.join(' ')}</p><small>{item.usage.aiRequests || 0} AI requests · {(item.usage.textTokens || 0).toLocaleString()} tokens · {item.usage.voiceTurns || 0} voice turns</small>{admin && <Button variant="outline" disabled={busy || reason.trim().length < 5} onClick={async () => { setBusy(true); try { setTranscript(await getTutorSupportTranscript(item.sessionRef, reason)); notify('Audited support transcript opened.'); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); } }}>Open full transcript for support</Button>}</article>) : <Empty title="No completed tutor sessions">A summary is created when a student ends a Tutor session.</Empty>}</section>
    <section className="panel stack"><h2>Safety notifications</h2><p>Notifications identify the concern and action without repeating the child’s message.</p>{events.length ? events.map((item) => <article className="card" key={item.eventRef}><div className="spread"><strong>{item.studentName} · {item.category.replace('_', ' ')}</strong><span className="pill">{item.severity}</span></div><p>{item.action}</p><small>{item.notificationStatus} · {item.reviewStatus} · {new Date(item.createdAt).toLocaleString()}</small>{admin && item.reviewStatus !== 'resolved' && <Button variant="outline" disabled={busy || reason.trim().length < 5} onClick={() => void run(() => reviewTutorSafetyEvent(item.eventRef, 'resolved', reason), 'Safety event reviewed and resolved.')}>Resolve with audit note</Button>}</article>) : <p>No safety notifications.</p>}</section>
    {admin && <><section className="panel stack"><h2>Support reason</h2><Input aria-label="Support and review reason" placeholder="Required for transcript access, review, or purge" value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} /></section><section className="panel stack"><h2>Transcript retention cleanup</h2><p>Transcripts remain forever unless an Admin explicitly performs this cleanup. Summaries, usage and audit records are preserved.</p><label className="stack" htmlFor="purge-days"><span>Older than days</span><Input id="purge-days" type="number" min="1" max="3650" value={days} onChange={(event) => { setDays(event.target.value); setPreview(null); }} /></label><div className="button-row"><Button variant="outline" disabled={busy} onClick={async () => { try { setPreview(await previewTutorTranscriptPurge(Number(days))); } catch (cause) { setError(errorMessage(cause)); } }}>Dry-run preview</Button><Button className="primary" disabled={busy || !preview || reason.trim().length < 5} onClick={() => void run(() => purgeTutorTranscripts(Number(days), reason), 'Selected transcript content purged.')}>Confirm PURGE TRANSCRIPTS</Button></div>{preview && <p className="source-note">{preview.turnCount} turns in {preview.sessionCount} sessions before {new Date(preview.cutoff).toLocaleString()} will be redacted.</p>}</section>{transcript && <section className="panel stack"><h2>Audited support transcript · {transcript.studentName}</h2>{transcript.turns.map((turn) => <article className="card" key={turn.turnRef}><strong>{turn.role}</strong><p>{turn.content}</p>{turn.purged && <small>Content purged</small>}</article>)}</section>}</>}
  </div>;
}
