export const subjects = [
  {
    id: "maths",
    name: "Mathematics",
    symbol: "∑",
    color: "blue",
    topic: "Numbers, patterns & possibilities",
    topics: ["Fractions", "Angles", "Coordinates"],
    course: "iLower Secondary",
  },
  {
    id: "science",
    name: "Science",
    symbol: "⚗",
    color: "green",
    topic: "Understand the world around you",
    topics: ["States of matter", "Forces", "Circuits"],
    course: "iLower Secondary",
  },
  {
    id: "english",
    name: "English",
    symbol: "Aa",
    color: "orange",
    topic: "Read closely. Express yourself.",
    topics: ["Inference", "Language choices", "Writing"],
    course: "iLower Secondary",
  },
  {
    id: "ict",
    name: "ICT",
    symbol: "⌘",
    color: "purple",
    topic: "Explore how technology works",
    topics: ["Networks", "Algorithms", "Hardware"],
    course: "iLower Secondary",
  },
];
export const questions = [
  {
    id: "m1",
    subject: "maths",
    topic: "Fractions",
    title: "A fraction of the whole",
    prompt:
      "A garden is divided into 8 equal sections. Three sections have flowers. What percentage of the garden has flowers?",
    marks: 2,
    type: "numeric",
    answer: 37.5,
    unit: "%",
    diagram: "fraction",
    hints: [
      "Write the flower sections as a fraction of the whole.",
      "Convert 3/8 to a decimal, then multiply by 100.",
    ],
    explanation:
      "Three of eight equal sections gives 3 ÷ 8 = 0.375. Multiplying by 100 gives 37.5%.",
    points: ["Write 3/8 or 0.375.", "Convert to 37.5%."],
    source: "Original demo · Number skills · Question 1",
  },
  {
    id: "m2",
    subject: "maths",
    topic: "Angles",
    title: "Find the missing angle",
    prompt: "The angles in this triangle are 50°, 60° and x°. Find x.",
    marks: 2,
    type: "numeric",
    answer: 70,
    unit: "°",
    diagram: "triangle",
    hints: [
      "The interior angles of a triangle add up to 180°.",
      "Subtract the two known angles from 180°.",
    ],
    explanation: "The known angles add to 110°. The missing angle is 180° − 110° = 70°.",
    points: ["Use 180 − (50 + 60).", "Find x = 70°."],
    source: "Original demo · Geometry · Question 2",
  },
  {
    id: "m3",
    subject: "maths",
    topic: "Coordinates",
    title: "Read the coordinate",
    prompt:
      "Point P is 4 units to the right of the origin and 3 units above it. What is its y-coordinate?",
    marks: 1,
    type: "numeric",
    answer: 3,
    unit: "",
    diagram: "coordinates",
    hints: ["The y-coordinate measures the vertical position."],
    explanation: "Coordinates are written (x, y). Point P is (4, 3), so its y-coordinate is 3.",
    points: ["Identify the y-coordinate as 3."],
    source: "Original demo · Coordinates · Question 3",
  },
  {
    id: "s1",
    subject: "science",
    topic: "States of matter",
    title: "When a solid becomes a liquid",
    prompt: "Explain what happens to the arrangement and movement of particles when a solid melts.",
    marks: 3,
    type: "written",
    diagram: "particles",
    hints: [
      "Compare how particles move in a solid and a liquid.",
      "Consider what happens when particles gain energy.",
    ],
    explanation:
      "Particles gain energy. They leave their fixed positions and can move past one another, while remaining close together. The particles themselves do not melt or get bigger.",
    points: [
      "Particles gain energy.",
      "They leave their fixed arrangement.",
      "They move past one another and remain close.",
    ],
    source: "Original demo · Matter · Question 1",
  },
  {
    id: "s2",
    subject: "science",
    topic: "Forces",
    title: "A balanced pair",
    prompt:
      "A box has a 12 N force to the right and an 8 N force to the left. What is the resultant force to the right?",
    marks: 2,
    type: "numeric",
    answer: 4,
    unit: "N",
    diagram: "forces",
    hints: ["The two forces act in opposite directions."],
    explanation: "Subtract the opposing forces: 12 − 8 = 4 N to the right.",
    points: ["Subtract 8 from 12.", "State 4 N to the right."],
    source: "Original demo · Forces · Question 2",
  },
  {
    id: "s3",
    subject: "science",
    topic: "Circuits",
    title: "Complete the circuit",
    prompt: "Why does the lamp go out when the switch in a simple series circuit is opened?",
    marks: 2,
    type: "written",
    diagram: "circuit",
    hints: ["Does the current still have a complete conducting path?"],
    explanation:
      "Opening the switch breaks the conducting path. Current stops flowing through the lamp, so it goes out.",
    points: ["The conducting path is broken.", "No current flows through the lamp."],
    source: "Original demo · Electricity · Question 3",
  },
  {
    id: "e1",
    subject: "english",
    topic: "Inference",
    title: "Read between the lines",
    prompt:
      "“Maya checked the clock again. Her untouched breakfast had gone cold.” What can you infer about Maya? Support your answer with evidence.",
    marks: 2,
    type: "written",
    diagram: "reading",
    hints: [
      "Think about why someone might repeatedly check the time.",
      "Use a short quotation to support a plausible interpretation.",
    ],
    explanation:
      "Maya may be anxious about an upcoming event: she checks the clock repeatedly and is too distracted to eat. Other interpretations can be valid if supported by the text.",
    points: ["Give a plausible inference.", "Support it with relevant textual evidence."],
    source: "Original demo · Reading · Question 1",
  },
  {
    id: "e2",
    subject: "english",
    topic: "Language choices",
    title: "Words that make a picture",
    prompt:
      "“The wind clawed at the shutters.” Identify the language technique and explain its effect.",
    marks: 2,
    type: "written",
    diagram: "reading",
    hints: ["The wind is given an action associated with a living creature."],
    explanation:
      "Personification presents the wind as an aggressive creature. “Clawed” suggests force and creates a threatening atmosphere.",
    points: ["Identify personification.", "Explain the effect of the specific word choice."],
    source: "Original demo · Language · Question 2",
  },
  {
    id: "e3",
    subject: "english",
    topic: "Writing",
    title: "Set the scene",
    prompt:
      "Write three sentences describing an empty train station at night. Use one sensory detail and one effective verb.",
    marks: 3,
    type: "written",
    diagram: "reading",
    hints: ["What can be heard or seen? Choose details that establish a mood."],
    explanation:
      "There are many valid responses. A strong response uses a precise sensory detail, deliberate verb choice and clear sentences to establish a mood.",
    points: ["Use a sensory detail.", "Choose an effective verb.", "Write coherent sentences."],
    source: "Original demo · Writing · Question 3",
  },
  {
    id: "i1",
    subject: "ict",
    topic: "Networks",
    title: "Follow the connection",
    prompt: "Explain the role of a router in a home network connected to the internet.",
    marks: 2,
    type: "written",
    diagram: "network",
    hints: ["Think about moving data between different networks."],
    explanation:
      "A router forwards data packets between networks, such as the home network and the internet. It uses destination addressing to decide where to send them.",
    points: [
      "Connects and forwards data between networks.",
      "Uses destination information to route packets.",
    ],
    source: "Original demo · Networks · Question 1",
  },
  {
    id: "i2",
    subject: "ict",
    topic: "Algorithms",
    title: "Trace the algorithm",
    prompt: "An algorithm starts with x = 3, doubles x, then adds 4. What is the final value of x?",
    marks: 2,
    type: "numeric",
    answer: 10,
    unit: "",
    diagram: "algorithm",
    hints: ["Follow the instructions in order: multiply before adding."],
    explanation: "Start with 3. Double it to get 6, then add 4 to get 10.",
    points: ["Calculate 3 × 2 = 6.", "Calculate 6 + 4 = 10."],
    source: "Original demo · Algorithms · Question 2",
  },
  {
    id: "i3",
    subject: "ict",
    topic: "Hardware",
    title: "Choose the right device",
    prompt: "Give one input device and one output device, and explain the role of each.",
    marks: 4,
    type: "written",
    diagram: "network",
    hints: ["An input device sends data into a computer. An output device presents information."],
    explanation:
      "For example, a keyboard enters characters and commands; a monitor displays visual output. Other correct devices and explanations are valid.",
    points: [
      "Name an input device.",
      "Explain its input role.",
      "Name an output device.",
      "Explain its output role.",
    ],
    source: "Original demo · Hardware · Question 3",
  },
];
export function initialState() {
  return {
    students: [
      {
        id: "alex",
        name: "Alex",
        initial: "A",
        level: "iLower Secondary",
        subjects: ["maths", "science", "english", "ict"],
      },
      {
        id: "jamie",
        name: "Jamie",
        initial: "J",
        level: "iPrimary",
        subjects: ["maths", "science", "english"],
      },
      {
        id: "sam",
        name: "Sam",
        initial: "S",
        level: "iGCSE",
        subjects: ["maths", "science", "english", "ict"],
      },
    ],
    attempts: [],
    exams: [],
    reviews: [],
    documents: [],
    files: [],
    assignments: [
      {
        id: "welcome-alex",
        studentId: "alex",
        subject: "maths",
        title: "Explore fractions",
        due: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
        questionId: "m1",
        completed: false,
      },
      {
        id: "welcome-jamie",
        studentId: "jamie",
        subject: "science",
        title: "Discover particles",
        due: new Date(Date.now() + 86400000).toISOString().slice(0, 10),
        questionId: "s1",
        completed: false,
      },
    ],
    plans: {},
  };
}
export const credentials = [
  { id: "parent", name: "Parent", role: "parent", password: "parent123" },
  { id: "alex", name: "Alex", role: "student", password: "alex123" },
  { id: "jamie", name: "Jamie", role: "student", password: "jamie123" },
  { id: "sam", name: "Sam", role: "student", password: "sam123" },
];
