"""add flashcard learning domain

Revision ID: 63f925e43652
Revises: 0003_retrieval_preflight
Create Date: 2026-09-19 07:33:30.890893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '63f925e43652'
down_revision: Union[str, None] = '0003_retrieval_preflight'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_decks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_ref', sa.String(length=56), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('card_limit', sa.Integer(), nullable=False),
    sa.Column('generation_key', sa.String(length=100), nullable=False),
    sa.Column('generation_metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('released_by', sa.Uuid(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','review','released','superseded')", name='ck_flashcard_deck_status'),
    sa.CheckConstraint('card_limit BETWEEN 1 AND 100', name='ck_flashcard_deck_limit'),
    sa.ForeignKeyConstraint(['content_version_id'], ['textbook_topic_content_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['topic_id'], ['textbook_topics.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generation_key'),
    sa.UniqueConstraint('public_ref')
    )
    op.create_index(op.f('ix_flashcard_decks_content_version_id'), 'flashcard_decks', ['content_version_id'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_status'), 'flashcard_decks', ['status'], unique=False)
    op.create_index(op.f('ix_flashcard_decks_topic_id'), 'flashcard_decks', ['topic_id'], unique=False)
    op.create_table('flashcard_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_ref', sa.String(length=56), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('current_ordinal', sa.Integer(), server_default='1', nullable=False),
    sa.Column('scheduler_version', sa.String(length=40), server_default='akuru-sm2-v1', nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active','completed','abandoned')", name='ck_flashcard_session_status'),
    sa.CheckConstraint('current_ordinal > 0', name='ck_flashcard_session_ordinal'),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_ref'),
    sa.UniqueConstraint('request_key')
    )
    op.create_index(op.f('ix_flashcard_sessions_deck_id'), 'flashcard_sessions', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcard_sessions_status'), 'flashcard_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_flashcard_sessions_student_id'), 'flashcard_sessions', ['student_id'], unique=False)
    op.create_table('flashcard_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('public_ref', sa.String(length=56), nullable=False),
    sa.Column('deck_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('front', sa.Text(), nullable=False),
    sa.Column('back', sa.Text(), nullable=False),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('source_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='review_required', nullable=False),
    sa.Column('validation_warnings', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('review_required','approved','rejected','superseded')", name='ck_flashcard_version_status'),
    sa.CheckConstraint('ordinal > 0 AND version_number > 0', name='ck_flashcard_version_numbers'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deck_id'], ['flashcard_decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['retrieval_chunks.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id', 'ordinal', 'version_number', name='uq_flashcard_version'),
    sa.UniqueConstraint('public_ref')
    )
    op.create_index(op.f('ix_flashcard_versions_deck_id'), 'flashcard_versions', ['deck_id'], unique=False)
    op.create_index(op.f('ix_flashcard_versions_status'), 'flashcard_versions', ['status'], unique=False)
    op.create_table('flashcard_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('card_version_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rating IN ('again','difficult','good','easy')", name='ck_flashcard_review_rating'),
    sa.CheckConstraint('interval_days >= 0', name='ck_flashcard_review_interval'),
    sa.ForeignKeyConstraint(['card_version_id'], ['flashcard_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['flashcard_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_key'),
    sa.UniqueConstraint('session_id', 'card_version_id', name='uq_flashcard_session_card')
    )
    op.create_index(op.f('ix_flashcard_reviews_due_at'), 'flashcard_reviews', ['due_at'], unique=False)
    op.create_index(op.f('ix_flashcard_reviews_session_id'), 'flashcard_reviews', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flashcard_reviews_session_id'), table_name='flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_reviews_due_at'), table_name='flashcard_reviews')
    op.drop_table('flashcard_reviews')
    op.drop_index(op.f('ix_flashcard_versions_status'), table_name='flashcard_versions')
    op.drop_index(op.f('ix_flashcard_versions_deck_id'), table_name='flashcard_versions')
    op.drop_table('flashcard_versions')
    op.drop_index(op.f('ix_flashcard_sessions_student_id'), table_name='flashcard_sessions')
    op.drop_index(op.f('ix_flashcard_sessions_status'), table_name='flashcard_sessions')
    op.drop_index(op.f('ix_flashcard_sessions_deck_id'), table_name='flashcard_sessions')
    op.drop_table('flashcard_sessions')
    op.drop_index(op.f('ix_flashcard_decks_topic_id'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_status'), table_name='flashcard_decks')
    op.drop_index(op.f('ix_flashcard_decks_content_version_id'), table_name='flashcard_decks')
    op.drop_table('flashcard_decks')
    # ### end Alembic commands ###
