"""add weakness diagnoses and recommendations

Revision ID: aea6ead467da
Revises: b0bea02e8860
Create Date: 2026-09-14 06:33:52.100741
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aea6ead467da'
down_revision: Union[str, None] = 'b0bea02e8860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weakness_diagnoses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('result_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('dimension', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('occurrence_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('minor','moderate','major')", name='ck_weakness_diagnosis_severity'),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1 AND occurrence_number > 0', name='ck_weakness_diagnosis_values'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_id'], ['assessment_results.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['textbook_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('result_id', 'unit_id', 'category', name='uq_weakness_diagnosis_result_unit_category')
    )
    op.create_index(op.f('ix_weakness_diagnoses_category'), 'weakness_diagnoses', ['category'], unique=False)
    op.create_index(op.f('ix_weakness_diagnoses_created_at'), 'weakness_diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_weakness_diagnoses_result_id'), 'weakness_diagnoses', ['result_id'], unique=False)
    op.create_index(op.f('ix_weakness_diagnoses_student_id'), 'weakness_diagnoses', ['student_id'], unique=False)
    op.create_index(op.f('ix_weakness_diagnoses_subject_id'), 'weakness_diagnoses', ['subject_id'], unique=False)
    op.create_index(op.f('ix_weakness_diagnoses_unit_id'), 'weakness_diagnoses', ['unit_id'], unique=False)
    op.create_table('improvement_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('diagnosis_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=False),
    sa.Column('activity_question_version_id', sa.Uuid(), nullable=True),
    sa.Column('activity_type', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('success_condition', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("activity_type IN ('review','targeted_practice','spaced_retry','unit_check')", name='ck_improvement_recommendation_activity'),
    sa.CheckConstraint("review_status IN ('approved','pending_review','rejected')", name='ck_improvement_recommendation_review'),
    sa.ForeignKeyConstraint(['activity_question_version_id'], ['official_question_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['weakness_diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['retrieval_chunks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['textbook_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diagnosis_id', 'activity_type', name='uq_improvement_recommendation_activity')
    )
    op.create_index(op.f('ix_improvement_recommendations_created_at'), 'improvement_recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_diagnosis_id'), 'improvement_recommendations', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_review_status'), 'improvement_recommendations', ['review_status'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_student_id'), 'improvement_recommendations', ['student_id'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_subject_id'), 'improvement_recommendations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_improvement_recommendations_unit_id'), 'improvement_recommendations', ['unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_improvement_recommendations_unit_id'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_subject_id'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_student_id'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_review_status'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_diagnosis_id'), table_name='improvement_recommendations')
    op.drop_index(op.f('ix_improvement_recommendations_created_at'), table_name='improvement_recommendations')
    op.drop_table('improvement_recommendations')
    op.drop_index(op.f('ix_weakness_diagnoses_unit_id'), table_name='weakness_diagnoses')
    op.drop_index(op.f('ix_weakness_diagnoses_subject_id'), table_name='weakness_diagnoses')
    op.drop_index(op.f('ix_weakness_diagnoses_student_id'), table_name='weakness_diagnoses')
    op.drop_index(op.f('ix_weakness_diagnoses_result_id'), table_name='weakness_diagnoses')
    op.drop_index(op.f('ix_weakness_diagnoses_created_at'), table_name='weakness_diagnoses')
    op.drop_index(op.f('ix_weakness_diagnoses_category'), table_name='weakness_diagnoses')
    op.drop_table('weakness_diagnoses')
    # ### end Alembic commands ###
