"""initial schema

Revision ID: ce0f8e5c5f0e
Revises:
Create Date: 2026-09-12 02:25:50.617415
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce0f8e5c5f0e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phase1_active', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.bulk_insert(sa.table('courses',
        sa.column('id', sa.String()), sa.column('name', sa.String()), sa.column('phase1_active', sa.Boolean())), [
        {'id': 'iprimary', 'name': 'iPrimary', 'phase1_active': False},
        {'id': 'ilower-secondary', 'name': 'iLower Secondary', 'phase1_active': False},
        {'id': 'igcse', 'name': 'iGCSE', 'phase1_active': True},
    ])
    op.bulk_insert(sa.table('subjects', sa.column('id', sa.String()), sa.column('name', sa.String())), [
        {'id': 'english', 'name': 'English'},
        {'id': 'maths', 'name': 'Maths'},
        {'id': 'ict', 'name': 'ICT'},
        {'id': 'biology', 'name': 'Biology'},
        {'id': 'chemistry', 'name': 'Chemistry'},
        {'id': 'physics', 'name': 'Physics'},
        {'id': 'french', 'name': 'French'},
        {'id': 'human-biology', 'name': 'Human Biology'},
    ])
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','parent','student')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('review_state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('textbook','reference','past_paper','mark_scheme','examiner_report')", name='ck_documents_kind'),
    sa.CheckConstraint("review_state IN ('pending','reviewed','published','rejected')", name='ck_documents_review_state'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key'),
    sa.UniqueConstraint('sha256')
    )
    op.create_index(op.f('ix_documents_subject_id'), 'documents', ['subject_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_student_profiles_parent_id'), 'student_profiles', ['parent_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('paper_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('question_number', sa.String(length=40), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('review_state', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("review_state IN ('pending','reviewed','published','rejected')", name='ck_questions_review_state'),
    sa.CheckConstraint('marks > 0', name='ck_questions_marks'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paper_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'course_id', 'subject_id', name='uq_question_scope'),
    sa.UniqueConstraint('paper_id', 'question_number', name='uq_paper_question_number')
    )
    op.create_table('student_progressions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade IN (10, 11)', name='ck_progression_grade'),
    sa.CheckConstraint('term IN (1, 2, 3)', name='ck_progression_term'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', 'grade', 'term', name='uq_student_progression_period')
    )
    op.create_index(op.f('ix_student_progressions_student_id'), 'student_progressions', ['student_id'], unique=False)
    op.create_index('uq_current_progression_per_student', 'student_progressions', ['student_id'], unique=True, postgresql_where=sa.text('is_current'))
    op.create_table('student_subjects',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('student_id', 'subject_id')
    )
    op.create_table('textbook_units',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('textbook_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('unit_code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['textbook_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'course_id', 'subject_id', name='uq_unit_scope'),
    sa.UniqueConstraint('textbook_id', 'unit_code', name='uq_textbook_unit_code')
    )
    op.create_table('question_units',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['question_id', 'course_id', 'subject_id'], ['questions.id', 'questions.course_id', 'questions.subject_id'], name='fk_question_unit_question_scope', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id', 'course_id', 'subject_id'], ['textbook_units.id', 'textbook_units.course_id', 'textbook_units.subject_id'], name='fk_question_unit_unit_scope', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'unit_id')
    )
    op.create_table('term_coverage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('subject_id', sa.String(length=32), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grade IN (10, 11)', name='ck_coverage_grade'),
    sa.CheckConstraint('term IN (1, 2, 3)', name='ck_coverage_term'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id', 'course_id', 'subject_id'], ['textbook_units.id', 'textbook_units.course_id', 'textbook_units.subject_id'], name='fk_coverage_unit_scope', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'subject_id', 'grade', 'term', 'unit_id', name='uq_term_coverage')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('term_coverage')
    op.drop_table('question_units')
    op.drop_table('textbook_units')
    op.drop_table('student_subjects')
    op.drop_index('uq_current_progression_per_student', table_name='student_progressions', postgresql_where=sa.text('is_current'))
    op.drop_index(op.f('ix_student_progressions_student_id'), table_name='student_progressions')
    op.drop_table('student_progressions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_student_profiles_parent_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_documents_subject_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('courses')
    # ### end Alembic commands ###
