"""add subject marking and student working

Revision ID: ea52940bc7e7
Revises: b0bb33062cfc
Create Date: 2026-09-13 23:19:07.178330
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea52940bc7e7'
down_revision: Union[str, None] = 'b0bb33062cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_working_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('ocr_text', sa.Text(), server_default='', nullable=False),
    sa.Column('ocr_confidence', sa.Float(), server_default='0', nullable=False),
    sa.Column('ocr_metadata', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('byte_size > 0', name='ck_assessment_working_file_size'),
    sa.CheckConstraint('ocr_confidence BETWEEN 0 AND 1', name='ck_assessment_working_ocr_confidence'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['assessment_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.student_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_assessment_working_files_assessment_id'), 'assessment_working_files', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_working_files_question_id'), 'assessment_working_files', ['question_id'], unique=False)
    op.create_index(op.f('ix_assessment_working_files_student_id'), 'assessment_working_files', ['student_id'], unique=False)
    op.add_column('assessment_results', sa.Column('subject_engine', sa.String(length=80), server_default='general', nullable=False))
    op.add_column('assessment_results', sa.Column('subject_engine_version', sa.String(length=40), server_default='legacy', nullable=False))
    op.add_column('assessment_results', sa.Column('deterministic_checks', sa.JSON(), server_default='{}', nullable=False))
    op.alter_column('assessment_results', 'subject_engine', server_default=None)
    op.alter_column('assessment_results', 'subject_engine_version', server_default=None)
    op.alter_column('assessment_results', 'deterministic_checks', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_results', 'deterministic_checks')
    op.drop_column('assessment_results', 'subject_engine_version')
    op.drop_column('assessment_results', 'subject_engine')
    op.drop_index(op.f('ix_assessment_working_files_student_id'), table_name='assessment_working_files')
    op.drop_index(op.f('ix_assessment_working_files_question_id'), table_name='assessment_working_files')
    op.drop_index(op.f('ix_assessment_working_files_assessment_id'), table_name='assessment_working_files')
    op.drop_table('assessment_working_files')
    # ### end Alembic commands ###
